language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn run build
before_deploy:
  - cd dist/ngx-notifications
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: nFB+u69/l1fCbMkiKpbwxCAO+0SlWMQTE9ghrcJ2QlZQwe0DeKqlnzJXt63Ef1uA4x9yg8/vDVzeLjBr6SU7vOZlw2eCkgvg3drHpq7TEYCz/5tLQ8h4II3AkBB/ITRr18cQ0r5vDsy17RkGlQ2IS6vYxuqZ9ov6Sjbn4JxAxMms44MFoAq0rvbczIsh5Q/ogqyPCXJcI56CYOuBn6nlSe6BSZviRyT5xPT1xJViGokA7PFzJPnAt+dg1a/U6fqnaJ1Gz6T6BVGJp7fQr0f4rr+YTWDiRutkGB6YzszOK70vB+2050AwdnupM51dR4Qrq5W+QxXkZkxGeaVMwFjRGofRY++q2r8yShQa1/N2/ntRqzHsTKUk2/nyEx2BL0PcgGJvCEVTQOkwaC+Hdh+QuD1Gv2gkFtxxigcRQosb9sw59QCB+/iq7NkO8kkeTW0DgPwo2zMj1r288Gh7q1taAgySQEtVVX6M22v5MYC0FVhu75F1K8gwSLQ/CMBICmTttPlvbTTCTSzoi48dPzcb8091uNo7M8pX4knE+jZl3jofwXYuonbrfXT9joe9r0jgeMkwrrk6tcIRpPcM/EwfTe6AP5prIqF9hKG0ewjqMXza4XCcsbl3h3SphCmv8hWl14ZT1ujyy6AQWV64Gw6dpKMQ1vJsu+V8eAirZGhkezg=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: MeMFT9uhC2UdzZaEjXiloK/yHRlB2Q5k5/gPbxmJim09v7bzu0dEdusNpWuwbZJY13KXF+pXh1UPa1ICuI/GogQ7+waUldsTE7qCWDxyOAPsZIffPvJLlX4Xnkcod/QaJL1xmb9lgqxMy1jUh0gI3qGmqQ5ZQpWTkQtlnoSoQvJd3FqA1MqVl2WvzUq4ok6rAfM29oX1oVGY3Eo/pvaCms0EyL5HZzYSTYe3mUt1lagT7W2pg9IaEyf1rgHIoReoIsL9RRsu2Luj1XJd4rR1+kR3G3ndmcs5s6XtJK+XpworMEwDjSb1y+gl2FQAhwzqvGW+A7k2u7smENtp9r8qr42T7hVB5hRj4IVnuV3VRG/TLGtQ5YTdMKzV4+IUOfXlZtKKTKxhTG36E1nlSaXs9HQcHwbCguPjYf2wDdDoe5GcaJubStCWVCVgBATg5/A7dUfbTaFfxksVNPNy7yID9n04L8N0kyHljaWOs6VHLnIoTNWRRRitsRBaydwMtIZB6ikijSwqp1WSwKvB8mHCpktB4IWLhhURRtIVY7SP/efHXwIMSM25izOKmRneLIJjiTGxNSAgWvmOTWYAgVEofsXGHEvgQPIqAx177cHv6oWJHS4WpxJACsXarMzwDzHeEbfUPelOc6Vae+zuphtnbsjHfp+pePuZk0w1NEDVJwc=
    on_success: never
    on_failure: always
    on_pull_requests: false
