language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn run build
before_deploy:
  - cd dist/ngx-notifications
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: lbZXs0kIlOEFUgvw2L8Hfi4sDem0EYgWiHWw7JiQ8hfT02B6/1fEyhzDkHOUw3qvZB19v8KXjnVSkI/C8DV0KmjJN1eE/ZPj4KHIfY28qClGrhHrv47+1cUVW8a+lB/2IFt4QEfXqoCl2my+tLqBXqvOs223rT9+5kvnrLlrP7iX0p2cHdwbLBpasa21H6Rl+LLXKYF1uJZwmA8bn3UipnEsiDyt2NnDGhDTDqTwiXFtSFXn5ZrrjCPWQrkKXQDGbuN6LZzC0Q9mK5JqBdhkPlxV3i5IIQm4Q6rfl+J0xYRWiXYH7zjlvoFxQkZnpiN1AEHzglc2tN54aHOR5MOhUHMD3MYRex3gKaUrleSph7ffvpj/HSAUXTQXSXp0Io3mtiYL6swZTmuCMwiuDKDRGu8GrOlthJZ/UHHMheZPc9yrTAFXPkbI6xD6LFvnwnvE420zNv4IEX5HqSepnM2uUDRwv/amZgva897E38Bk+c3CKP9DOx/M+M93uTju+njLSLy4auZ7keYsIgPSh2JldXO+UVNbcZEAQsNgLueRwoPmsP9nTk5CSxFhNXRuyIf8nGeamTmNMsOwiQ1PFJoKK8TcH2NA3EQoI/Q6c02VBJUcRW90fJNuYq9PdW6JG+/Cnilpu6pHvOAXTgCeJQYfGaQIbIzebto8kNl1vDGJt4A=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: MeMFT9uhC2UdzZaEjXiloK/yHRlB2Q5k5/gPbxmJim09v7bzu0dEdusNpWuwbZJY13KXF+pXh1UPa1ICuI/GogQ7+waUldsTE7qCWDxyOAPsZIffPvJLlX4Xnkcod/QaJL1xmb9lgqxMy1jUh0gI3qGmqQ5ZQpWTkQtlnoSoQvJd3FqA1MqVl2WvzUq4ok6rAfM29oX1oVGY3Eo/pvaCms0EyL5HZzYSTYe3mUt1lagT7W2pg9IaEyf1rgHIoReoIsL9RRsu2Luj1XJd4rR1+kR3G3ndmcs5s6XtJK+XpworMEwDjSb1y+gl2FQAhwzqvGW+A7k2u7smENtp9r8qr42T7hVB5hRj4IVnuV3VRG/TLGtQ5YTdMKzV4+IUOfXlZtKKTKxhTG36E1nlSaXs9HQcHwbCguPjYf2wDdDoe5GcaJubStCWVCVgBATg5/A7dUfbTaFfxksVNPNy7yID9n04L8N0kyHljaWOs6VHLnIoTNWRRRitsRBaydwMtIZB6ikijSwqp1WSwKvB8mHCpktB4IWLhhURRtIVY7SP/efHXwIMSM25izOKmRneLIJjiTGxNSAgWvmOTWYAgVEofsXGHEvgQPIqAx177cHv6oWJHS4WpxJACsXarMzwDzHeEbfUPelOc6Vae+zuphtnbsjHfp+pePuZk0w1NEDVJwc=
    on_success: never
    on_failure: always
    on_pull_requests: false
