name: Test package
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v5

      # prepare
      - uses: actions/setup-node@v5.0.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile

      # build
      - run: yarn run build
